name = "alive_chocolate_bass-a0e6"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "alive_chocolate_bass-a0e6_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "alive_chocolate_bass-a0e6.wasm"
command = "npm run build:release"
